spring:
  application:
    name: oauth2Server
  resources:
    chain:
      enabled: true
      cache: false
server:
  port: 9999
  context-path: /uaa
logging:
  level:
    org.springframework.security: info
    org.springframework.security.web.util: warn
    org.springframework.web: warn
security:
  user:
    name: user
    password: password
    role:
    - USER
    - ADMIN
    - ACCOUNT