spring:
  application:
    name: oauth2Server
  resources:
    static-locations:
    - dist/
server:
  port: 9999
  context-path: /uaa
logging:
  level:
    org.springframework.security: debug
    org.springframework.security.web.util: warn
    org.springframework.web: debug
security:
  user:
    name: user
    password: password
    role:
    - USER
    - ADMIN
    - ACCOUNT
  oauth2:
    resource:
      jwt:
        key-value: sambhav