spring:
  application:
    name: webfront-ui
  resources:
    chain:
      enabled: true
      cache: false
server:
  port: 80
security:
  oauth2:
    sso:
      login-path: /login-samsoft
    client:
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
      client-id: acme
      client-secret: acmesecret
      access-token-validity-seconds: 36000
    resource:
      user-info-uri: /me
      jwt:
        key-value: sambhav
logging:
  level:
    org.springframework.security: info
    org.springframework.security.web.util: warn
    org.springframework.web: warn