spring:
  application:
    name: crm-web
  data:
    mongodb:
      database: samsoft-test
server:
  port: 9001
logging:
  level:
    org.springframework.security: info
    org.springframework.security.web.util: warn
    org.springframework.web: warn